@Library(['eumlib@feature/build_oc_pipeline']) _

import at.gv.brz.justiz3.jenkins.JU30BuildConfig
import at.gv.brz.jueu.job.JuEuJobConfiguration

def buildConfig = new JU30BuildConfig()
def euJobConfig = new JuEuJobConfiguration()

genericPipeline(buildConfig, euJobConfig)